bitfinity-network/bit-fusion-sdk

scripts/icrc_deploy.sh

Update icrc_deploy.sh to remove spender

---

src/minter-contract-utils/Cargo.toml
src/minter-contract-utils/build.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-841

Improve error message when forge not found

---

Cargo.lock
Cargo.toml
scripts/rune/batch.yaml
scripts/rune_deploy.sh
src/create_bft_bridge_tool/Cargo.toml
src/create_bft_bridge_tool/src/main.rs
src/integration-tests/Cargo.toml
src/integration-tests/tests/dfx_tests/runes.rs
src/integration-tests/tests/state_machine_tests/rune.rs
src/rune-bridge/Cargo.toml
src/rune-bridge/src/canister.rs
src/rune-bridge/src/lib.rs
src/rune-bridge/src/ops.rs
src/rune-bridge/src/rune_info.rs
src/rune-bridge/src/scheduler.rs
src/rune-bridge/src/state.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-744

Allow rune bridge to work with multiple runes

---

Cargo.lock
Cargo.toml
scripts/dfx_tests.sh
src/integration-tests/tests/dfx_tests/runes.rs
src/rune-bridge/src/canister.rs
src/rune-bridge/src/key.rs
src/rune-bridge/src/ledger.rs
src/rune-bridge/src/ops.rs
src/rune-bridge/src/state.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-848

Allow multiple inputs for rune bridge

---

.github/workflows/release.yml
scripts/build.sh

Make minter canisters release that looks like on the link below
https://github.com/bitfinity-network/bit-fusion-sdk/releases/tag/v0.2.0-2-gd84c9a7

Release minter canisters wasms as release package

---

solidity/src/BftBridge.sol
src/icrc2-minter/src/tasks.rs
src/integration-tests/tests/context/mod.rs
src/integration-tests/tests/pocket_ic_integration_test/erc20_minter.rs
src/minter-contract-utils/src/bft_bridge_api.rs

https://infinityswap.atlassian.net/browse/EPROD-883

[EPROD-883] Additional integration tests

---

solidity/src/BftBridge.sol
solidity/src/contract_tests/BftBridge.t.sol
src/minter-contract-utils/src/bft_bridge_api.rs

Token list method and tests

---

Cargo.lock
Cargo.toml
scripts/build_solidity.sh
solidity/src/BftBridge.sol
solidity/src/FeeCharge.sol
solidity/src/contract_tests/BftBridge.t.sol
solidity/src/contract_tests/FeeCharge.t.sol
solidity/src/interfaces/IFeeCharge.sol
src/create_bft_bridge_tool/src/main.rs
src/erc20-minter/src/canister.rs
src/icrc2-minter/src/canister.rs
src/icrc2-minter/src/state.rs
src/icrc2-minter/src/state/config.rs
src/integration-tests/tests/context/mod.rs
src/integration-tests/tests/dfx_tests/runes.rs
src/integration-tests/tests/pocket_ic_integration_test/erc20_minter.rs
src/integration-tests/tests/pocket_ic_integration_test/icrc2_minter.rs
src/integration-tests/tests/pocket_ic_integration_test/mod.rs
src/integration-tests/tests/state_machine_tests/btc.rs
src/minter-contract-utils/build.rs
src/minter-contract-utils/src/bft_bridge_api.rs
src/minter-contract-utils/src/build_data.rs
src/minter-contract-utils/src/evm_bridge.rs
src/minter-contract-utils/src/fee_charge_api.rs
src/minter-contract-utils/src/lib.rs

https://infinityswap.atlassian.net/browse/EPROD-906

[EPROD-906] Separate fee charge contract

---

scripts/deploy/deploy_functions.sh
scripts/icrc_deploy.sh
src/create_bft_bridge_tool/src/main.rs

ICRC bridge deploy script update

---

src/icrc2-minter/src/canister.rs
src/icrc2-minter/src/constant.rs
src/icrc2-minter/src/lib.rs
src/icrc2-minter/src/operation.rs
src/icrc2-minter/src/state.rs
src/icrc2-minter/src/tasks.rs
src/integration-tests/tests/context/mod.rs
src/integration-tests/tests/dfx_tests/runes.rs
src/integration-tests/tests/pocket_ic_integration_test/erc20_minter.rs
src/integration-tests/tests/pocket_ic_integration_test/icrc2_minter.rs
src/integration-tests/tests/state_machine_tests/btc.rs
src/minter-contract-utils/src/operation_store.rs
src/rune-bridge/src/core/deposit.rs
src/rune-bridge/src/memory.rs

Issue ticket link: 
* https://infinityswap.atlassian.net/browse/EPROD-836
* https://infinityswap.atlassian.net/browse/EPROD-894

Keep log and state changes for ICRC2 bridge

---

Cargo.lock
Cargo.toml
docs/deploy.md
src/btc-bridge/Cargo.toml
src/create_bft_bridge_tool/Cargo.toml
src/icrc2-minter/Cargo.toml
src/integration-tests/Cargo.toml
src/integration-tests/tests/state_machine_tests/btc.rs
src/rune-bridge/Cargo.toml

Update IC dependencies to get rid of lmdb-sys build issues

---

Cargo.lock
Cargo.toml

Upgrade curve25519-dalek to fix RUSTSEC-2024-0344

---

Cargo.lock
Cargo.toml
src/integration-tests/tests/dfx_tests/erc20_minter.rs
src/integration-tests/tests/utils/error.rs
src/integration-tests/tests/utils/mod.rs
src/minter-contract-utils/Cargo.toml
src/minter-contract-utils/build.rs
src/minter-contract-utils/tests/build_data/mod.rs
src/solidity-helper/Cargo.toml
src/solidity-helper/src/error.rs
src/solidity-helper/src/lib.rs

EPROD-851 check for changes before rebuilding solidity contracts

---

src/bridge-utils/src/common.rs
src/bridge-utils/src/lib.rs
src/bridge-utils/src/operation_store.rs
src/erc20-minter/src/canister.rs
src/erc20-minter/src/tasks.rs
src/icrc2-minter/src/canister.rs
src/icrc2-minter/src/tasks.rs
src/integration-tests/tests/dfx_tests/erc20_minter.rs
src/rune-bridge/src/canister.rs
src/rune-bridge/src/core/deposit.rs

[EPROD-949] Use typed fields for the pagination

---

src/integration-tests/tests/dfx_tests/erc20_minter.rs
src/rune-bridge/src/core/deposit.rs
src/rune-bridge/src/core/index_provider.rs

EPROD-854 use pagination for get rune list

---

src/bridge-canister/src/lib.rs
src/bridge-did/src/order.rs

Signed mint order getters

---

solidity/src/BftBridge.sol
src/bridge-utils/src/bft_events.rs

https://infinityswap.atlassian.net/browse/EPROD-959

[EPROD-959] Charged fee in minted event

---

Cargo.lock
src/rune-bridge/src/constants.rs
src/rune-bridge/src/core/withdrawal.rs
src/rune-bridge/src/lib.rs
src/rune-bridge/src/state.rs

Eventually we only need to cache the fee rate.

EPROD 884 F25 data that doesnt change frequently is not cached

---

Cargo.lock
Cargo.toml
scripts/tests/dfx_tests.sh
src/integration-tests/tests/dfx_tests/runes.rs
src/integration-tests/tests/utils/rune_helper.rs
src/rune-bridge/src/core/withdrawal.rs
src/rune-bridge/src/ops.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-962
Fixed operation split which didn't process the inner operations.

EPROD-962 integration tests with multi runes

---

src/integration-tests/tests/state_machine_tests/btc.rs

EPROD-778 concurrent btc txs tests

---

Cargo.lock
Cargo.toml
src/bridge-canister/src/bridge.rs
src/bridge-utils/src/bft_events.rs
src/rune-bridge/Cargo.toml
src/rune-bridge/src/core/deposit.rs
src/rune-bridge/src/core/index_provider.rs
src/rune-bridge/src/core/mod.rs
src/rune-bridge/src/core/rune_inputs.rs
src/rune-bridge/src/core/utxo_provider.rs
src/rune-bridge/src/core/withdrawal.rs
src/rune-bridge/src/ops.rs

This is the first PR with unit tests of Rune bridge. It covers only small part of things to cover, but it's a start. All the non-trivial fixes or improvements that should be done related to what is covered by this PR are listed as separate tickets in JIRA.
Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-960

[EPROD-960] Unit tests for Rune bridge (minter notification + AwaitInputs)

---

.github/workflows/build-test.yml
scripts/tests/dfx_tests.sh

This PR reduces the "setup environment" CI phase from 12m to 25s.
https://infinityswap.atlassian.net/browse/EPROD-987

[EPROD-987] Improve CI build times - part 1

---

Cargo.lock
src/bridge-canister/Cargo.toml
src/bridge-canister/src/runtime/scheduler.rs
src/bridge-did/src/error.rs
src/integration-tests/tests/dfx_tests/runes.rs
src/rune-bridge/src/ops.rs
src/rune-bridge/src/ops/tests/await_inputs.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-975

[EPROD-975] Bail our of wait for inputs operations in case it cannot be progressed

---

solidity/remappings.txt
solidity/soldeer.lock
solidity/src/BftBridge.sol
solidity/src/FeeCharge.sol
solidity/src/WrappedToken.sol
solidity/src/abstract/TokenManager.sol
solidity/src/test_contracts/NewBftBridge.sol
solidity/src/test_contracts/TestWTM.sol
solidity/src/test_contracts/UUPSProxy.sol
solidity/test/contract_tests/BftBridge.t.sol

Update OpenZeppelin imports to standardized paths across Solidity contracts and remappings

---

.github/workflows/build-test-deploy.yml
.github/workflows/build-test.yml

https://infinityswap.atlassian.net/browse/EPROD-999

[EPROD-999] Fix rustc and dfx version on CI. Remove unused workflow config entries.

---

solidity/hardhat.config.ts
solidity/hardhat.md
solidity/soldeer.lock
solidity/src/BftBridge.sol
solidity/src/WrappedToken.sol
solidity/src/WrappedTokenDeployer.sol
solidity/src/abstract/TokenManager.sol
solidity/src/interfaces/IWrappedToken.sol
solidity/src/interfaces/IWrappedTokenDeployer.sol
solidity/tasks/deploy-bft.ts
solidity/tasks/deploy-wrapped-token-deployer.ts
solidity/test/contract_tests/BftBridge.t.sol
src/bridge-deployer/src/commands/mod.rs
src/bridge-deployer/src/contracts.rs
src/bridge-tool/src/main.rs
src/bridge-utils/src/lib.rs
src/integration-tests/tests/context/mod.rs
src/integration-tests/tests/context/stress.rs
src/integration-tests/tests/dfx_tests/brc20_bridge/ctx.rs
src/integration-tests/tests/dfx_tests/runes.rs
src/integration-tests/tests/pocket_ic_integration_test/erc20_bridge.rs
src/integration-tests/tests/pocket_ic_integration_test/mod.rs
src/integration-tests/tests/state_machine_tests/btc.rs

https://infinityswap.atlassian.net/browse/EPROD-1009

[EPROD-1009] Separate token deployer contract

---

src/bridge-deployer/src/cli.rs
src/bridge-deployer/src/commands/deploy.rs
src/bridge-deployer/src/commands/mod.rs
src/bridge-deployer/src/commands/reinstall.rs
src/bridge-deployer/src/commands/upgrade.rs

EPROD-1019 filter logs on debug; print important information on stdout

---

src/bridge-deployer/src/commands/mod.rs
src/bridge-deployer/src/config/btc.rs
src/bridge-deployer/src/config/mod.rs
src/bridge-did/src/init/bridge_data.rs
src/bridge-did/src/init/btc.rs
src/bridge-did/src/init/mod.rs
src/btc-bridge/src/canister.rs
src/btc-bridge/src/state.rs
src/integration-tests/tests/state_machine_tests/btc.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-1013

[EPROD-1013] Init btc bridge with ckBTC parameters

---

Cargo.lock
src/bridge-canister/src/bridge.rs
src/bridge-canister/src/runtime.rs
src/bridge-canister/src/runtime/scheduler.rs
src/bridge-canister/src/runtime/state.rs
src/bridge-did/src/operations/erc20.rs
src/erc20-bridge/Cargo.toml
src/erc20-bridge/src/canister.rs
src/erc20-bridge/src/ops.rs
src/erc20-bridge/src/state.rs
src/integration-tests/tests/pocket_ic_integration_test/erc20_bridge.rs
src/rune-bridge/src/ops/tests/send_mint_order.rs

https://infinityswap.atlassian.net/browse/EPROD-1002

[EPROD-1002] Services in erc20 bridge

---

just/code_check.just

Make `just clippy` just work

---

Cargo.lock
Cargo.toml
btc-deploy/docker-compose.yml
just/fetch_dependencies.just
src/bridge-tool/src/main.rs
src/integration-tests/tests/context/mod.rs
src/integration-tests/tests/context/stress.rs
src/integration-tests/tests/dfx_tests/brc20_bridge/ctx.rs
src/integration-tests/tests/dfx_tests/runes.rs
src/integration-tests/tests/pocket_ic_integration_test/erc20_bridge.rs
src/integration-tests/tests/state_machine_tests/btc.rs

https://infinityswap.atlassian.net/browse/EPROD-1028

[Eprod-1028] admin-only mint IC endpoint

---

solidity/src/BftBridge.sol
solidity/test/contract_tests/BftBridge.t.sol

EPROD-1001 unit tests for bft bridge

---

src/brc20-bridge/src/canister.rs
src/bridge-canister/src/operation_store.rs
src/bridge-canister/src/runtime/scheduler.rs
src/bridge-client/src/brc20_bridge_client.rs
src/bridge-client/src/erc20_bridge_client.rs
src/bridge-client/src/icrc2_bridge_client.rs
src/bridge-client/src/rune_bridge_client.rs
src/bridge-did/src/op_id.rs
src/btc-bridge/src/canister.rs
src/erc20-bridge/src/canister.rs
src/icrc2-bridge/src/canister.rs
src/integration-tests/tests/dfx_tests/brc20_bridge/ctx.rs
src/integration-tests/tests/dfx_tests/runes.rs
src/integration-tests/tests/pocket_ic_integration_test/erc20_bridge.rs
src/integration-tests/tests/pocket_ic_integration_test/icrc2_bridge.rs
src/rune-bridge/src/canister.rs

https://infinityswap.atlassian.net/browse/EPROD-1036

[EPROD-1036] Get operation list pagination fix

---

src/bridge-canister/src/runtime/service.rs
src/bridge-canister/src/runtime/service/timer.rs
src/bridge-deployer/src/commands/mod.rs
src/bridge-deployer/src/config/erc.rs
src/bridge-did/src/init/erc20.rs
src/erc20-bridge/src/canister.rs
src/erc20-bridge/src/memory.rs
src/erc20-bridge/src/state.rs
src/integration-tests/tests/context/mod.rs

https://infinityswap.atlassian.net/browse/EPROD-1007

[EPROD-1007] Delay in services execution

---

.gitignore
Cargo.lock
solidity/script/DeployErc20.s.sol
solidity/script/DeployWrappedToken.s.sol
solidity/src/abstract/TokenManager.sol
src/bridge-deployer/Cargo.toml
src/bridge-deployer/src/commands/deploy.rs
src/bridge-deployer/src/commands/mod.rs
src/bridge-deployer/src/commands/wrap_token_type.rs
src/bridge-deployer/src/contracts.rs
src/bridge-deployer/src/evm.rs
src/bridge-did/src/operations/erc20.rs
src/bridge-tool/Cargo.toml
src/bridge-tool/src/flow/mod.rs
src/bridge-tool/src/main.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-1034

Deployer fixes / deploy, withdraw commands in bridge-tool

---

Cargo.lock
src/bridge-deployer/Cargo.toml
src/bridge-deployer/src/commands/deploy.rs
src/bridge-deployer/src/commands/mod.rs
src/bridge-deployer/src/contracts.rs
src/bridge-tool/Cargo.toml
src/bridge-tool/src/flow/mod.rs
src/bridge-utils/Cargo.toml
src/bridge-utils/src/lib.rs
src/bridge-utils/src/native.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-1051

Option to transfer ETH to bridge canister on deploy

---

src/btc-bridge/src/ops.rs
src/integration-tests/tests/context/brc20_bridge.rs
src/integration-tests/tests/context/btc_bridge.rs
src/integration-tests/tests/context/rune_bridge.rs
src/integration-tests/tests/context/stress/brc20.rs
src/integration-tests/tests/pocket_ic_integration_test/btc_bridge.rs
src/integration-tests/tests/utils/btc_rpc_client.rs
src/integration-tests/tests/utils/btc_transfer_helper.rs
src/integration-tests/tests/utils/btc_wallet.rs
src/integration-tests/tests/utils/mod.rs

https://infinityswap.atlassian.net/browse/EPROD-1126

EPROD 1126 BTC bridge roundtrip integration test

---

src/bridge-canister/src/runtime/state/config.rs
src/bridge-client/src/btc_bridge_client.rs
src/btc-bridge/src/ops.rs
src/integration-tests/tests/context/btc_bridge.rs
src/integration-tests/tests/context/stress.rs
src/integration-tests/tests/context/stress/btc.rs
src/integration-tests/tests/pocket_ic_integration_test/btc_bridge.rs
src/integration-tests/tests/utils/btc_rpc_client.rs
src/integration-tests/tests/utils/btc_transfer_helper.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-984

EPROD-984 btc bridge stress test

---

src/bridge-utils/src/evm_bridge.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-738

EPROD-738 fixed query evm params

---

src/erc20-bridge/src/state.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-1176

EPROD-1176 base evm delays were not set

---

src/bridge-client/src/btc_bridge_client.rs
src/btc-bridge/src/canister.rs
src/integration-tests/Cargo.toml
src/integration-tests/tests/context/btc_bridge.rs
src/integration-tests/tests/pocket_ic_integration_test/btc_bridge.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-1032

[EPROD-1032] Update BTC bridge API

---

Cargo.lock
Cargo.toml
src/bridge-canister/Cargo.toml
src/bridge-canister/src/runtime/service/mint_tx.rs
src/bridge-tool/src/flow/mod.rs
src/bridge-utils/src/btf_events.rs
src/bridge-utils/src/evm_link.rs
src/bridge-utils/src/evm_link/evm_rpc_canister_client.rs
src/integration-tests/tests/dfx_tests/bridge_deployer.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-1182

EPROD 1182 parse revert reason from jsonrpc error

---

just/dfx.just
src/bridge-deployer/src/evm.rs
src/integration-tests/tests/dfx_tests/bridge_deployer.rs
src/integration-tests/tests/dfx_tests/mod.rs
src/integration-tests/tests/utils/dfx.rs
src/integration-tests/tests/utils/mod.rs
src/integration-tests/tests/utils/test_evm/bitfinity/dfx.rs

Issue ticket link: https://infinityswap.atlassian.net/browse/EPROD-1188

EPROD-1188 compatibility with dfx 0.26 with dfx tests
